baseURL = "https://blog.putnam.computer/"
languageCode = "en-us"
title = "Sydney's Tech Blog"
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]] 
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Contact"
url="mailto:sydney.putnam@proton.me"
weight = 4

[markup]
    [markup.highlight]
        noClasses = false

[params]
    mainSectionTitle = "Posts"
    description = "Hi there! This is where I post notes on tech projects I've been working on. You can also find me on [GitHub](https://github.com/passportmidi/) and [LinkedIn](https://www.linkedin.com/in/sydney-putnam/)."
    tagsOverview = false